import  express from "express";
import { configDotenv } from "dotenv";    
import {connectDB} from "./config/db.js";
import adminRouter from "./routes/adminRoutes.js";
import userRouter from "./routes/userRoutes.js";
import productRouter from "./routes/productRoutes.js";
import wishlistRouter from "./routes/wishlistRoutes.js";
import uploadRouter from "./routes/uploadRoutes.js";
import paymentRouter from "./routes/paymentRoutes.js";
import allProductRouter from "./routes/allProductsRoutes.js";
import authRouter from "./routes/authRoutes.js";
import cartRouter from "./routes/cartRoutes.js";
import contactLensRouter from "./routes/contactLensRoutes.js";
import healthRouter from "./routes/healthRoutes.js";
import cors from "cors";
configDotenv();
const app = express();
const PORT = process.env.PORT || 4000;
connectDB();
app.use(express.json());
app.use(cors());
app.use('/api', adminRouter);
app.use('/api', allProductRouter);
app.use('/api', authRouter);
app.use('/api', cartRouter);
// app.use('/api/v1', categoryRouter);
app.use('/api', contactLensRouter);
app.use('/api', healthRouter);
app.use('/api', userRouter);
app.use('/api', wishlistRouter);
app.use('/api', productRouter);
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));

